#!/usr/bin/env python
import os
import sys
import glob

env = SConscript("godot-cpp/SConstruct")

env.Append(CPPPATH=["Source/"])
env.Append(CPPDEFINES=["HOT_RELOAD_ENABLED"])

sources = glob.glob("**/*.cpp", recursive = True)

if env["platform"] == "macos":
    library = env.SharedLibrary(
        "../addons/CurveMesh3D/bin/Bopimo.{}.{}.framework/libgdexample.{}.{}".format(
            env["platform"], env["target"], env["platform"], env["target"]
        ),
        source=sources,
    )
else:
    library = env.SharedLibrary(
        "../addons/CurveMesh3D/bin/CurveMesh3D{}{}".format(env["target"].replace("template_release", "").replace("template_", "."), env["SHLIBSUFFIX"]),
        source=sources,
    )

Default(library)
